### ISSUE TITLE
Can't get tox + pdm to work

### ISSUE THREAD

**Issue by warsaw** [pdm-project/tox-pdm#15]
I'm clearly doing something wrong, although I've tried both methods of integrating tox + pdm that are [described here](https://pdm.fming.dev/usage/advanced/#use-tox-as-the-runner).

* [Draft PR without tox-pdm](https://gitlab.com/warsaw/flufl.lock/-/merge_requests/52)
* [Draft PR using tox-pdm](https://gitlab.com/warsaw/flufl.lock/-/merge_requests/51)

A few things I've discovered, rightly or wrongly.

* When attempting to integrate with `tox-pdm`, I find that I need to use the keyword `groups` rather than `sections` in my `tox.ini`.  That seems to jive with what the `tox-pdm` [README implies](https://github.com/pdm-project/tox-pdm), but not what the [pdm docs say](https://pdm.fming.dev/usage/advanced/#use-tox-as-the-runner).
* When attempting to integrate with `tox-pdm`, I also have to invoke this via `pdm run tox` since `tox-pdm` is not installed into my global tox.
* When attempting to integrate without `tox-pdm` I find that the `pdm install -G <group>` doesn't seem to install the dependencies into the venv.  It's not clear that it should, but even with `use_venv` set, I don't have to have to repeat myself if I can avoid it.

I would love to get this to work!

**Comment by frostming** [comment]
The without `tox-pdm` branch can work with a little tweak, the ini file should be:
```ini
[tox]
envlist = {py37,py38,py39,py310},qa,docs
skip_missing_interpreters = true
isolated_build = true

[testenv]
setenv =
    PDM_IGNORE_SAVED_PYTHON="1"
    PYTHONPATH = ''
...
```
I've updated the doc with the correct content.

The with `tox-pdm` branch might have some conflicts with `setuptools` and can't work locally if the global `python` is Python 2. Not sure if CI would be fine. This should be a bug though.

**Comment by warsaw** [comment]
@frostming Yay!  Thank you.  The no-tox-pdm version works with the changes just as you suggest.  I'll try the with-tox-pdm version once you release a version with that fix.  I think I prefer the no-tox-pdm version in general though because --unless I'm mistaken-- the with-tox-pdm version requires you to run it via `pdm run tox` or install `tox-pdm` in the global tox environment.

Did you also see the question about `groups` vs `sections`?  That's only relevant for the with-tox-pdm version, but it still appears to be a conflict in the documentation.

**Comment by warsaw** [comment]
Oh also, you're right.  I'm on a Mac so `python` is `/usr/bin/python` a.k.a. Python 2.7.16

**Comment by frostming** [comment]
Yes, the doc is out-of-date, I've updated it. In fact for the `no-tox-pdm` branch, if you have pdm installed globally, it doesn't need to appear in `deps` as well.

The release is on the way.

**Comment by warsaw** [comment]
> Yes, the doc is out-of-date, I've updated it.

Thanks.

>  In fact for the no-tox-pdm branch, if you have pdm installed globally, it doesn't need to appear in deps as well.

I thought about that, but I also need to get pdm installed into my CI images, which should be easy though I haven't gotten to that yet.

> The release is on the way.

Thanks again.
