### ISSUE TITLE
Tox3 installs package with deps, leading to error incase of changed pypi index in pdm

### ISSUE THREAD

**Issue by alex007sirois** [pdm-project/tox-pdm#23]
My project uses a private PyPI server which has private python libraries.
Configuring PDM to use it works well, however tox3 still tries to install package with pip by installing dependencies, which leads to a failed lookup of private packages in the public pypi server.

logs:
```
action: py38, msg: installpkg
cwd: /home/alex/work/doo_parsers
cmd: /home/alex/.pyenv/versions/3.8.12/bin/python3.8 -m pip install --exists-action w .tox/.tmp/package/1/doo-parsers-22.3.4+d20220407.tar.gz -t .tox/py38/__pypackages__/3.8/lib
Processing ./.tox/.tmp/package/1/doo-parsers-22.3.4+d20220407.tar.gz
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
ERROR: Could not find a version that satisfies the requirement doo-utils (from doo-parsers) (from versions: none)
ERROR: No matching distribution found for doo-utils
```
Tox4 does not seems to have this problem.
Configuring pip with the PyPI is a valid workaround.

**Comment by frostming** [comment]
Configuring `install_command` with `--no-deps` might do the trick?

**Comment by alex007sirois** [comment]
Do you mean changing tox's `install_command ` to force using pdm to install configs instead of pip?
I did not consider this.
I will have to try tomorrow to see how this works.
Thank you

**Comment by frostming** [comment]
> Do you mean changing tox's `install_command ` to force using pdm to install configs instead of pip? I did not consider this. I will have to try tomorrow to see how this works. Thank you

No, but add `--no-deps` option to pip's `install_command`

**Comment by alex007sirois** [comment]
Oh, yes, I understand now.
This should work around my problem even better.
I'm not on my work computer right now and can't fully test this, but it should work.
I will be able to confirm tomorrow.

**Comment by alex007sirois** [comment]
I can confirm that adding `install_command=python -m pip install {opts} {packages}` to `[testenv]` does fix this problem.
