### ISSUE TITLE
use `sync` instead of `install`

### ISSUE THREAD

**Issue by davidism** [pdm-project/tox-pdm#30]
For Flask and other Pallets projects, we currently lock all dev dependencies using `pip-compile`. That way, when new contributors run the tests, they are guaranteed to use a known working set of dependencies, instead of possibly getting a new version of some tool with an incompatibility. I'd like that same guarantee in tox-pdm, so it will do `pdm sync -d -G tests` and use the lock file, instead of `install` which might update the lock file instead.

**Comment by frostming** [comment]
SGTM, PR welcome!
