### ISSUE TITLE
feat: select lockfile to use, or alternative way of specifying `direct_minimal_versions`

### ISSUE THREAD

**Issue by inigohidalgo** [pdm-project/tox-pdm#53]
In my testing, as well as using tox to select the python version, I would like to be able to select the lowest set of compatible dependencies and test against those.

The manual process I follow at the moment is to:

## setup

`pdm lock -L pdm/lock/lowest.lock --strategy direct_minimal`
`pdm lock -L pdm/lock/latest.lock`

## Matrix testing

I have a pipeline which runs the following process for various versions of python

### venv_1

`pdm sync -L pdm/lock/lowest.lock`
`pytest .`

### venv_2

`pdm sync -L pdm/lock/latest.lock`
`pytest .`

# Q

Is there a way to do that with the currently-implemented functionality?

**Comment by frostming** [comment]
> Is there a way to do that with the currently-implemented functionality?


Use `PDM_LOCKFILE` env var

**Comment by inigohidalgo** [comment]
thank you
